name: "Run unit test when pushing codes"
on: ["push"]
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4
      - name: Print a message
        run: echo "Here is just a message"
      - name: Install packages
        run: npm install
      - name: Run unit test
        run: npm test
